export const FETCH_WEATHER = "COMMAND/FETCH_WEATHER_FOR_LAT_LNG";
export const FETCH_METRICDATA = "COMMAND/FETCH_METRICDATA"
export const METRIC_DATA_RECEIVED = "EVENT/METRIC_DATA_RECEIVED";
export const METRIC_DATA_FAILED = "EVENT/METRIC_DATA_RECEIVED";
export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED";
